// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EmpresaIT.Models;

namespace EmpresaIT.Migrations
{
    [DbContext(typeof(EmpleadosContext))]
    [Migration("20201109212235_CreacionInicial")]
    partial class CreacionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("model.Empleado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmpresaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PuestoDeTrabajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sueldo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("model.Empresa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("model.Empleado", b =>
                {
                    b.HasOne("model.Empresa", null)
                        .WithMany("Empleados")
                        .HasForeignKey("EmpresaID");
                });
#pragma warning restore 612, 618
        }
    }
}
